### ISSUE TITLE
Walkscore status 2 searchInProgress error

### ISSUE THREAD

**Issue by waleed3298** [insightindustry/walkscore-api#8]
Why does all of my walkscore api searches give a status 2 and never return the walkscore

**Comment by insightindustry** [comment]
Afraid I don’t know - that’s really a question you’d have to ask the WalkScore team. Do you get the same result when you use the WalkScore UI? Their documentation recommends that if a Walk Score is consistently unavailable via the API that the UI may return the result: https://www.walkscore.com/professional/api.php
